# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/menus

main:
  - label: Accueil
    title: This is the <b>first<b> menu item.
    link: homepage
    class: homepage
  - label: Services
    link: services
    submenu:
        - label: Création SiteWeb
          link: service/creation-site-web
        - label: Développement Web
          class: menu-item-class
          link: service/developpement-applications-web
        - label: Hébergement Web
          link: service/hebergement-web 
  - label: A Propos
    link: aurora/apropos
    class: apropos
  - label: Hébergement Web
    link: https://hosting.aurora.cm
    class: bolt-site
    title: Meilleur hébergement web au Cameroun

footer:
    - label: Acceuil
      link: /
    - label: Services
      link: services
    - label: Contact
      link: contact
